name: "Terraform GitHub Actions"
on:
  push:
    branches:
      - master
jobs:
  terraform:
    name: "Terraform Init"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Terraform Initialization"
        uses: meenudevops/assess@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "init"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

